FORMAT: 1A
HOST: https://evci.int.bqws.io/

# EVCI (v1.0)
EVCI is an event collector service.

## Evci endpoint [/v1.0/event/{type}]

This enpoint allow to submit events o a given type. The event must be submited in json format. 

Example: **/event/log:Error**

+ Parameters
    + type (required, string, `log:Error`) ... String `type` of the product to perform action with. Has example value. 
    
### Publish event [POST]

###Version###

Avaliable from version 0.12.0

###Errors###
|Status|Error|Description|
|------|-----|-----------|
|422   |unprocessable_entity|When body is missing or invalid.|
|401  |unauthorized|If the access_token is not associated with any user.|

+ Request (application/json)

    + Headers

            Authorization : Bearer {token}                  

    + Body                                 

            {
                "Field 1": "Description of field 1",
                "Field 2": "Description of field 2"
            }

+ Response 202 
